{% set name = "quickjs" %}
{% set version = "1.19.4" %}

package:
  # The package is named python-quickjs to leave `quickjs` available for a binary of the wrapped library
  name: python-{{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1205953abc24ff757f4a795304d5d61e4bf1e555c9ef6ec96a132d4b95535484
  patches:
    - setup.patch

build:
  number: 4

requirements:
  build:
    - {{ compiler('c') }}  # [not win]
    - {{ stdlib("c") }}    # [not win]
    - {{ compiler('m2w64_c') }}  # [win]
    - {{ stdlib("m2w64_c") }}    # [win]
  host:
    - libpython  # [win]
    - python
    - pip
    - setuptools
  run:
    - python

test:
  files:
    - test_quickjs.py
  imports:
    - quickjs
  requires:
    - pip
  commands:
    - pip check
    - python -m unittest

about:
  home: https://github.com/PetterS/quickjs
  summary: 'Wrapping the quickjs C library.'
  description: |
    Python wrapper around https://bellard.org/quickjs/
    Translates types like str, float, bool, list, dict and combinations thereof to and from Javascript.
    QuickJS is currently thread-hostile, so this wrapper makes sure that all calls to the same JS runtime comes from the same thead.
  license: MIT
  license_family: MIT
  license_file:
    - LICENSE
    - LICENSE-quickjs
  doc_url: https://bellard.org/quickjs/
  dev_url: https://github.com/PetterS/quickjs

extra:
  recipe-maintainers:
    - m-rossi
    - fcollonval
